// Starter German sentences for sentence drills, written for this project
// (same license as the rest of the code). Short, everyday and made of common
// words, with real German capitals (nouns) and ß/umlauts where they belong.
// `scripts/build-sentences.py de` replaces this file with a larger set from
// Tatoeba (CC BY 2.0 FR).

const sentences: readonly string[] = [
  'Die Sonne scheint und der Himmel ist klar.',
  'Sie liest ein Buch im Garten.',
  'Wir gehen heute Morgen auf den Markt.',
  'Die Kinder spielen draußen im Park.',
  'Er trinkt jeden Morgen eine Tasse Tee.',
  'Unser Zug fährt um zehn Uhr ab.',
  'Die Katze schläft auf dem warmen Stuhl.',
  'Ich muss noch Brot und Milch kaufen.',
  'Der Weg ist lang, aber die Nacht ist ruhig.',
  'Bitte mach die Tür zu, wenn du gehst.',
  'Sie saßen im Gras und redeten lange.',
  'Das ist die beste Suppe, die ich kenne.',
  'Meine Schwester malt und zeichnet gern.',
  'Der Hund rennt durch den Garten.',
  'Wir essen heute Abend bei meinen Eltern.',
  'Am Wochenende fahren wir an den See.',
  'Kannst du mir bitte das Salz geben?',
  'Es regnet schon den ganzen Tag.',
  'Ich habe heute keine Zeit.',
  'Das Wasser ist noch sehr kalt.',
  'Er wohnt in einem kleinen Haus am Rand der Stadt.',
  'Wo ist der nächste Bahnhof?',
  'Die Straße ist nass vom Regen.',
  'Ich weiß nicht, was ich sagen soll.',
  'Wir haben viel Spaß zusammen.',
  'Der Lehrer erklärt die Aufgabe noch einmal.',
  'Mein Bruder spielt jeden Sonntag Fußball.',
  'Das Essen ist gleich fertig.',
  'Sie lacht über den alten Witz.',
  'Wie spät ist es jetzt?',
  'Im Winter wird es früh dunkel.',
  'Die Blumen im Fenster sind rot und gelb.',
  'Er hat seinen Schlüssel verloren.',
  'Ich freue mich auf die Ferien.',
  'Das Kind hat große Augen gemacht.',
  'Wir müssen morgen früh aufstehen.',
  'Der Kaffee ist heiß und stark.',
  'Sie hat einen neuen Job in der Stadt.',
  'Hast du heute schon gegessen?',
  'Das Fenster steht weit offen.',
  'Er liest jeden Tag die Zeitung.',
  'Die Kirche steht in der Mitte des Dorfes.',
  'Ich gehe gern im Wald spazieren.',
  'Das Wetter ist heute schön.',
  'Wir treffen uns um acht vor dem Kino.',
  'Sie singt ein Lied für ihre Mutter.',
  'Der Zug hat leider Verspätung.',
  'Kommst du heute Abend mit?',
  'Mein Vater arbeitet in einer großen Firma.',
  'Das Brot ist frisch und noch warm.',
  'Er stellt die Tasse auf den Tisch.',
  'Ich habe den Film schon gesehen.',
  'Die Kinder lernen in der Schule lesen.',
  'Wir wohnen seit drei Jahren hier.',
  'Das Meer ist heute ganz ruhig.',
  'Sie trägt einen roten Mantel.',
  'Er schreibt seiner Freundin einen Brief.',
  'Ich trinke lieber Wasser als Saft.',
  'Die Tür ist nicht abgeschlossen.',
  'Wann beginnt das Spiel?',
  'Der Garten ist voller Blumen.',
  'Sie hat ihre Hausaufgaben schon gemacht.',
  'Wir sitzen gern draußen in der Sonne.',
  'Das Auto steht vor dem Haus.',
  'Ich rufe dich später an.',
  'Er ist ein guter Freund.',
  'Die Stadt ist im Sommer sehr voll.',
  'Danke für deine Hilfe!',
  'Das war ein langer Tag.',
  'Sie kocht eine Suppe mit Gemüse.',
  'Der Himmel ist grau und es ist kalt.',
  'Ich lerne jeden Tag ein paar neue Wörter.',
  'Wir fahren mit dem Rad zur Arbeit.',
  'Er hört gern laute Musik.',
  'Das Zimmer ist hell und warm.',
  'Sie wartet an der Ecke auf den Bus.',
  'Hast du Lust auf einen Spaziergang?',
  'Die Uhr an der Wand ist stehen geblieben.',
  'Ich habe heute Nacht gut geschlafen.',
  'Der Kuchen schmeckt sehr gut.',
  'Er kauft Äpfel und Birnen auf dem Markt.',
  'Wir sehen uns nächste Woche.',
  'Die Kinder schlafen schon.',
  'Sie hat lange auf diesen Tag gewartet.',
  'Das Buch liegt auf dem Tisch.',
  'Ich verstehe die Frage nicht.',
  'Der Winter war dieses Jahr sehr mild.',
  'Er geht jeden Abend mit dem Hund raus.',
  'Wir brauchen noch Eier und Butter.',
  'Die Antwort ist ganz einfach.',
  'Sie spricht drei Sprachen.',
  'Das Licht in der Küche ist noch an.',
  'Ich habe meine Brille vergessen.',
  'Der Arzt sagt, ich soll mehr schlafen.',
  'Wir haben den ganzen Tag gearbeitet.',
  'Er erzählt gern Geschichten.',
  'Das Haus hat einen großen Garten.',
  'Sie öffnet langsam die Tür.',
  'Morgen soll es wieder regnen.',
  'Ich bin gleich wieder da.',
  'Die Vögel singen schon am frühen Morgen.',
  'Er fährt jeden Tag mit dem Zug.',
  'Wir spielen am Abend Karten.',
  'Das Geschäft ist am Sonntag geschlossen.',
  'Sie schreibt alles in ein kleines Heft.',
  'Ich möchte ein Glas Wasser, bitte.',
  'Der Film war spannend und lustig.',
  'Die Brücke führt über den Fluss.',
  'Er hat die Prüfung bestanden.',
  'Wir müssen jetzt leider gehen.',
  'Das Mädchen malt ein Bild von ihrer Katze.',
  'Sie hat den Brief noch nicht gelesen.',
  'Ich suche meine Schuhe.',
  'Der Tee ist noch zu heiß.',
  'Er wartet schon seit einer Stunde.',
  'Die Nacht war kalt und klar.',
  'Wir lachen viel, wenn wir zusammen sind.',
  'Das Spiel endet um neun Uhr.',
  'Sie fragt, ob du morgen Zeit hast.',
  'Ich gehe jetzt nach Hause.',
];

export default sentences;
