// Starter English sentences for sentence drills, written for this project
// (same license as the rest of the code). Short, everyday and made of common
// words. Many avoid f, v, z, x, q and j so sentence drills can start before
// those letters are unlocked. `scripts/build-sentences.py en` replaces this
// file with a larger set from Tatoeba (CC BY 2.0 FR).

const sentences: readonly string[] = [
  'The sun is out and the sky is clear.',
  'She reads a book in the garden.',
  'We are going to the market this morning.',
  'The children are playing in the park.',
  'He drinks a cup of tea each morning.',
  'Our train leaves at noon.',
  'The cat is sleeping on the warm chair.',
  'I need to buy some bread and milk.',
  'The road is long, but the night is calm.',
  'Please close the door when you go out.',
  'They sat on the grass and talked.',
  'This is the best soup I have had.',
  'My sister likes to paint and draw.',
  'The store opens early on Monday.',
  'It rained all day, so we stayed inside.',
  'The dog ran across the yard.',
  'A light wind came in through the window.',
  'Can you help me carry these bags?',
  'We had rice and beans to eat.',
  'The old man sat on a bench in the sun.',
  'Write your name at the top of the page.',
  'The meeting ended later than planned.',
  'She sang a song to the baby.',
  'He kept the letter in a small box.',
  'The garden is green again after the rain.',
  'I am learning to type with all ten fingers.',
  'The bus was late, so I walked home.',
  'Turn left at the corner and go straight on.',
  'Their house is next to the river.',
  'The teacher asked a hard question.',
  'Let us meet at the cafe at three.',
  'He smiled and shook my hand.',
  'The lamp on the desk is broken.',
  'Most people sleep better in a dark room.',
  'She runs in the park on Sunday.',
  'The lake was still and blue.',
  'Put the cups back on the shelf.',
  'I can hear birds singing outside.',
  'We spent the whole day at the beach.',
  'This street is quiet at night.',
  'The kids made a sand castle.',
  'Add a little salt to the pasta.',
  'He is reading the paper in the kitchen.',
  'The plants need water and sunlight.',
  'My brother works in a large hospital.',
  'The moon rose above the hills.',
  'Can I borrow your pencil?',
  'The bridge crosses a wide river.',
  'She lost her keys again.',
  'The bakery sells warm bread.',
  'Our team won the last game.',
  'The baby is asleep in the car.',
  'It is cold, so put on a coat.',
  'He opened the window to let in some air.',
  'The music was loud and happy.',
  'I left my bag on the train.',
  'The cake is in the oven.',
  'They planted trees along the road.',
  'Please speak a little more slowly.',
  'The museum is closed on Monday.',
  'A small boat sailed across the bay.',
  'She painted the walls light green.',
  'The kettle is on, and tea is coming.',
  'My uncle grows tomatoes and beans.',
  'The ship came into the harbor at dawn.',
  'We should start early tomorrow.',
  'The children sang and danced.',
  'He is always on time.',
  'The snow melted in the spring sun.',
  'She keeps a diary on her desk.',
  'The clock on the wall stopped.',
  'I would like a glass of water, please.',
  'Our neighbors are kind and helpful.',
  'The cook added onions to the pan.',
  'There is a small shop around the corner.',
  'The lesson starts in ten minutes.',
  'He kicked the ball into the goal.',
  'The pears on the table are ripe.',
  'This path leads down to the sea.',
  'Turn on the light, please.',
  'The pilot landed the plane gently.',
  'She bought a red hat at the market.',
  'Hold the rail when you go down the stairs.',
  'They walked along the beach at sunset.',
  'We are out of sugar.',
  'The library has many old books.',
  'A good night of sleep helps you learn.',
  'He hung his coat on the hook.',
  'The radio is too loud.',
  'I usually walk to school.',
  'The tea is still hot.',
  'She is good at math and science.',
  'The dog barked at the mailman.',
  'Can you pass me the salt?',
  'The leaves turn red and gold in autumn.',
  'There is a nest in that tree.',
  'Our garden is small but pretty.',
  'He rides his bike to work.',
  'The room was clean and bright.',
  'She is learning to play the piano.',
  'Please wait here until I return.',
  'This shirt is too big.',
  'We sat around the table and laughed.',
  'The stars are bright tonight.',
  'He put the plates in the sink.',
  'The trip took longer than we thought.',
  'I like to read in bed.',
  'A strong storm is coming.',
  'She tied her hair back.',
  'The orange cat climbed onto the roof.',
  'Let me think about it.',
  'The milk is in the cold box.',
  'Good typing comes with practice.',
  'Keep your eyes on the screen, not on the keys.',
  'Rest your hands lightly on the home row.',
  'Accuracy comes first, and speed will come later.',
  'Take a short break when your hands get tired.',
  'Sit up straight and relax your shoulders.',
  'We often have fish on Friday.',
  'The film was very funny.',
  'I have five apples in my bag.',
  'Every day is a new chance to learn.',
  'He gave me a nice gift.',
  'We live near a big forest.',
  'Never give up on your goals.',
  'She found a coin on the floor.',
  'The view from the hill is lovely.',
  'My family visits the farm every summer.',
  'The river flows into the sea.',
  'He felt better after a short rest.',
  'They moved to a new flat last year.',
  'The office is on the fifth floor.',
  'Fresh fruit is good for you.',
  'I forgot my umbrella at home.',
  'The fox jumped over the fence.',
  'Just do your best.',
  'The jar is full of jam.',
  'The quiet village has one shop.',
  'She asked a quick question.',
  'The zoo has two young zebras.',
  'The box was too heavy to lift.',
  'He fixed the old radio himself.',
  'We waited for the next train.',
  'Five friends went on a trip together.',
  'Her voice is soft and clear.',
  'The fire kept us warm all night.',
  'I prefer coffee with a little milk.',
  'He wore a blue jacket and a cap.',
  'Have you ever seen the ocean?',
  'Our flight leaves early in the morning.',
  'The wind blew the leaves off the trees.',
  'They often walk their dog after dinner.',
  'She folded the towels and put them away.',
  'If it is sunny, we will go swimming.',
  'The movie starts at seven.',
  'Few people were on the beach that day.',
  'The village is famous for its cheese.',
  'He likes to fish by the lake.',
  'We have a test on Friday.',
  'The view of the valley was wonderful.',
  'Please give me a call when you arrive.',
  'Six ducks swam across the pond.',
  'The office was very quiet after five.',
  'My favorite season is spring.',
  'Life in the city is busy.',
  'The juice is cold and sweet.',
  'He jogs in the park before work.',
  'This is my first visit to the coast.',
  'The fridge is empty again.',
  'The hotel is near the main square.',
  'Our cat loves to sleep in the sun.',
  'The farmer drove his tractor to the field.',
  'She has a calm and gentle voice.',
  'Please leave your shoes by the door.',
  'Most of the leaves have fallen.',
  'The doctor will see you now.',
  'The bus stop is across the road.',
  'He is the tallest boy in his class.',
  'The bread smells good.',
  'We climbed to the top of the hill.',
  'The soup needs a little more pepper.',
  'Hang the picture above the sofa.',
  'She is writing a letter to her aunt.',
  'The boat rocked on the waves.',
  'It is a long walk to the station.',
  'Turn the page and keep reading.',
  'The garden gate was open.',
  'He sat down and opened his laptop.',
  'The sand was warm under our toes.',
  'I usually eat lunch at one.',
  'The ducks are swimming in the pond.',
  'The children are learning to count.',
  'She smiled when she saw the cake.',
  'They are building a new school in town.',
  'We heard a strange sound outside.',
  'The lights in the hall are dim.',
  'He carried the tray into the room.',
  'Hot tea is nice on a cold day.',
  'She cut the bread into thin slices.',
  'This road goes all the way to the coast.',
];

export default sentences;
