// Starter Spanish sentences for sentence drills, written for this project
// (same license as the rest of the code). Short, everyday and made of common
// words, with accents, ñ and the opening ¿ and ¡ where they belong.
// `scripts/build-sentences.py es` replaces this file with a larger set from
// Tatoeba (CC BY 2.0 FR).

const sentences: readonly string[] = [
  'El sol brilla y el cielo está despejado.',
  'Ella lee un libro en el jardín.',
  'Vamos al mercado esta mañana.',
  'Los niños juegan en el parque.',
  'Él toma una taza de té cada mañana.',
  'Nuestro tren sale a las diez.',
  'El gato duerme en la silla.',
  'Todavía tengo que comprar pan y leche.',
  'El camino es largo, pero la noche es tranquila.',
  'Cierra la puerta cuando salgas, por favor.',
  'Se sentaron en la hierba y hablaron mucho.',
  'Es la mejor sopa que conozco.',
  'Mi hermana pinta y dibuja.',
  'El perro corre por el jardín.',
  'Esta noche cenamos con mis padres.',
  'El fin de semana vamos al lago.',
  '¿Me pasas la sal, por favor?',
  'Llueve desde esta mañana.',
  'Hoy no tengo tiempo.',
  'El agua todavía está muy fría.',
  'Vive en una casa pequeña a las afueras de la ciudad.',
  '¿Dónde está la estación más cercana?',
  'La calle está mojada por la lluvia.',
  'Ella canta una canción muy dulce.',
  'Mañana nos vamos de vacaciones.',
  'El café está demasiado caliente.',
  'Es tarde, tenemos que volver.',
  'Las flores del jardín huelen bien.',
  'Mi hermano trabaja en un restaurante.',
  'No entiendo esta pregunta.',
  'Todos llegaron a tiempo.',
  'La puerta de la sala está abierta.',
  'Ella espera el autobús delante de la oficina.',
  'Los pájaros cantan en los árboles.',
  'Caminamos durante dos horas.',
  '¿Tienes hambre?',
  'La tienda abre a las nueve.',
  'Perdió las llaves anoche.',
  'Ella habla tres idiomas.',
  'La comida estaba muy rica.',
  'Nos vemos delante del cine.',
  'El viento sopla fuerte esta noche.',
  'Los alumnos escuchan al profesor.',
  'Prefiero el té al café.',
  'Hoy el mar está tranquilo.',
  'Escribió una carta a su madre.',
  'Necesitamos una mesa más grande.',
  'La película empieza en diez minutos.',
  'Mi abuela hace una tarta de manzana.',
  'Ella abrió la ventana.',
  'Queda un poco de pan.',
  'Las hojas caen en otoño.',
  '¿Vienes con nosotros esta noche?',
  'Me alegro mucho de verte.',
  'La ciudad es bonita de noche.',
  'Lee el periódico cada mañana.',
  'El tren llega tarde.',
  'Hablamos de nuestros planes.',
  'Encontró un gatito en la calle.',
  'Hace buen tiempo, vamos a pasear.',
  'Este libro es muy interesante.',
  'Los niños vuelven de la escuela.',
  'Estoy buscando mis gafas.',
  'La cena está lista.',
  'Hay que girar a la izquierda después del puente.',
  'Ella lleva un vestido rojo.',
  'Visitamos un castillo antiguo.',
  'El médico llega en una hora.',
  'Me levanto temprano por la mañana.',
  'La nieve cubre las montañas.',
  'Compró una bicicleta nueva.',
  'Mis amigos viven cerca del mar.',
  'El museo cierra los lunes.',
  'Ella sonríe y dice hola.',
  'Llevamos una hora esperando.',
  'Los precios han vuelto a subir.',
  'Toca la guitarra por la noche.',
  'Tu idea es muy buena.',
  'El bebé por fin duerme.',
  'Voy a la playa con mis amigos.',
  'La cocina huele a pan recién hecho.',
  'Se le olvidó el paraguas.',
  'Ella aprobó el examen.',
  'Volvemos a casa.',
  '¿Qué hora es?',
  'El jardín está lleno de flores.',
  'No se puede correr en el pasillo.',
  'Ella aprende a nadar.',
  'El mercado tiene mucha vida los sábados.',
  'Te llamo mañana por la mañana.',
  'Las estrellas brillan en el cielo.',
  'Va al trabajo en metro.',
  'La sopa tiene demasiada sal.',
  'Bailamos toda la noche.',
  'Ella ordena su habitación.',
  'El lago se congela en invierno.',
  'Siento llegar tarde.',
  'Pone el vaso sobre la mesa.',
  '¡Buenas noches y hasta mañana!',
  '¡Qué buen tiempo hace hoy!',
];

export default sentences;
