// Starter French sentences for sentence drills, written for this project
// (same license as the rest of the code). Short, everyday and made of common
// words, with accents where they belong. Written without the space French
// typography puts before ? ! : and ;, as most people type online.
// `scripts/build-sentences.py fr` replaces this file with a larger set from
// Tatoeba (CC BY 2.0 FR).

const sentences: readonly string[] = [
  'Le soleil brille et le ciel est clair.',
  'Elle lit un livre dans le jardin.',
  'Nous allons au marché ce matin.',
  'Les enfants jouent dans le parc.',
  'Il boit une tasse de thé chaque matin.',
  'Notre train part à dix heures.',
  'Le chat dort sur la chaise.',
  'Je dois encore acheter du pain et du lait.',
  'La route est longue, mais la nuit est calme.',
  'Ferme la porte quand tu sors, merci.',
  'Ils sont assis dans l\'herbe et parlent longtemps.',
  'C\'est la meilleure soupe que je connaisse.',
  'Mon amie aime dessiner.',
  'Le chien court dans le jardin.',
  'Ce soir, nous mangeons chez mes parents.',
  'Le week-end, nous allons au lac.',
  'Tu peux me passer le sel, s\'il te plaît?',
  'Il pleut depuis ce matin.',
  'Je n\'ai pas le temps aujourd\'hui.',
  'L\'eau est encore très froide.',
  'Il habite dans une petite maison au bord de la ville.',
  'Où est la gare la plus proche?',
  'La rue est mouillée par la pluie.',
  'Elle chante une chanson très douce.',
  'Nous partons en vacances demain.',
  'Le café est trop chaud pour moi.',
  'Il est tard, il faut rentrer.',
  'Les fleurs du jardin sentent bon.',
  'Mon frère travaille dans un restaurant.',
  'Je ne comprends pas cette question.',
  'Tout le monde est arrivé à temps.',
  'La porte de la salle est ouverte.',
  'Elle attend le bus devant la poste.',
  'Les oiseaux chantent dans les arbres.',
  'Nous avons marché pendant deux heures.',
  'Est-ce que tu as faim?',
  'Le magasin ouvre à neuf heures.',
  'Il a perdu ses clés hier soir.',
  'Elle parle trois langues.',
  'Le repas était vraiment délicieux.',
  'On se retrouve devant le cinéma.',
  'Le vent souffle fort ce soir.',
  'Les élèves écoutent le professeur.',
  'Je préfère le thé au café.',
  'La mer est calme aujourd\'hui.',
  'Il a écrit une lettre à sa mère.',
  'Nous avons besoin d\'une plus grande table.',
  'Le film commence dans dix minutes.',
  'Ma grand-mère fait une tarte aux pommes.',
  'Elle a ouvert la fenêtre.',
  'Il reste un peu de pain.',
  'Les feuilles tombent en automne.',
  'Tu viens avec nous ce soir?',
  'Je suis très content de te voir.',
  'La ville est belle la nuit.',
  'Il lit le journal chaque matin.',
  'Le train est en retard.',
  'Nous parlons de nos projets.',
  'Elle a trouvé un petit chat dans la rue.',
  'Il fait beau, allons nous promener.',
  'Ce livre est très intéressant.',
  'Les enfants rentrent de l\'école.',
  'Je cherche mes lunettes.',
  'Le dîner est prêt.',
  'Il faut tourner à gauche après le pont.',
  'Elle porte une robe rouge.',
  'Nous avons visité un vieux château.',
  'Le médecin arrive dans une heure.',
  'Je me lève tôt le matin.',
  'La neige couvre les montagnes.',
  'Il a acheté un nouveau vélo.',
  'Mes amis habitent près de la mer.',
  'Le musée est fermé le lundi.',
  'Elle sourit et dit bonjour.',
  'Nous attendons depuis une heure.',
  'Les prix ont encore monté.',
  'Il joue de la guitare le soir.',
  'Ton idée est très bonne.',
  'Le bébé dort enfin.',
  'Je vais à la plage avec mes amis.',
  'La cuisine sent le pain chaud.',
  'Il a oublié son parapluie.',
  'Elle a réussi son examen.',
  'Nous rentrons à la maison.',
  'Quelle heure est-il?',
  'Le jardin est plein de fleurs.',
  'Il ne faut pas courir dans le couloir.',
  'Elle apprend à nager.',
  'Le marché est très animé le samedi.',
  'Je t\'appelle demain matin.',
  'Les étoiles brillent dans le ciel.',
  'Il prend le métro pour aller au travail.',
  'La soupe est trop salée.',
  'Nous avons dansé toute la nuit.',
  'Elle range sa chambre.',
  'Le lac est gelé en hiver.',
  'Je suis désolé pour le retard.',
  'Il pose le verre sur la table.',
  'Bonne nuit et à demain!',
  'Quel beau temps aujourd\'hui!',
];

export default sentences;
