// Starter Italian sentences for sentence drills, written for this project
// (same license as the rest of the code). Short, everyday and made of common
// words, with accents where they belong.
// `scripts/build-sentences.py it` replaces this file with a larger set from
// Tatoeba (CC BY 2.0 FR).

const sentences: readonly string[] = [
  'Il sole splende e il cielo è sereno.',
  'Lei legge un libro in giardino.',
  'Stamattina andiamo al mercato.',
  'I bambini giocano nel parco.',
  'Lui beve una tazza di tè ogni mattina.',
  'Il nostro treno parte alle dieci.',
  'Il gatto dorme sulla sedia.',
  'Devo ancora comprare pane e latte.',
  'La strada è lunga, ma la notte è tranquilla.',
  'Chiudi la porta quando esci, per favore.',
  'Si sono seduti sull\'erba e hanno parlato a lungo.',
  'È la zuppa più buona che conosca.',
  'Mia sorella dipinge e disegna.',
  'Il cane corre in giardino.',
  'Stasera ceniamo dai miei genitori.',
  'Nel fine settimana andiamo al lago.',
  'Mi passi il sale, per favore?',
  'Piove da stamattina.',
  'Oggi non ho tempo.',
  'L\'acqua è ancora molto fredda.',
  'Abita in una piccola casa ai margini della città.',
  'Dov\'è la stazione più vicina?',
  'La strada è bagnata per la pioggia.',
  'Lei canta una canzone molto dolce.',
  'Domani partiamo per le vacanze.',
  'Il caffè è troppo caldo per me.',
  'È tardi, dobbiamo tornare.',
  'I fiori del giardino hanno un buon profumo.',
  'Mio fratello lavora in un ristorante.',
  'Non capisco questa domanda.',
  'Sono arrivati tutti in tempo.',
  'La porta della sala è aperta.',
  'Lei aspetta l\'autobus davanti alla posta.',
  'Gli uccelli cantano sugli alberi.',
  'Abbiamo camminato per due ore.',
  'Hai fame?',
  'Il negozio apre alle nove.',
  'Ieri sera ha perso le chiavi.',
  'Lei parla tre lingue.',
  'Il pranzo era davvero buono.',
  'Ci vediamo davanti al cinema.',
  'Stasera tira un vento forte.',
  'Gli studenti ascoltano il professore.',
  'Preferisco il tè al caffè.',
  'Oggi il mare è calmo.',
  'Ha scritto una lettera a sua madre.',
  'Ci serve un tavolo più grande.',
  'Il film comincia tra dieci minuti.',
  'La nonna prepara una torta di mele.',
  'Lei ha aperto la finestra.',
  'È rimasto un po\' di pane.',
  'In autunno cadono le foglie.',
  'Vieni con noi stasera?',
  'Sono molto contento di vederti.',
  'La città è bella di notte.',
  'Legge il giornale ogni mattina.',
  'Il treno è in ritardo.',
  'Parliamo dei nostri progetti.',
  'Ha trovato un gattino per strada.',
  'Fa bel tempo, andiamo a fare una passeggiata.',
  'Questo libro è molto interessante.',
  'I bambini tornano da scuola.',
  'Sto cercando gli occhiali.',
  'La cena è pronta.',
  'Dopo il ponte bisogna girare a sinistra.',
  'Lei porta un vestito rosso.',
  'Abbiamo visitato un vecchio castello.',
  'Il medico arriva tra un\'ora.',
  'La mattina mi alzo presto.',
  'La neve copre le montagne.',
  'Ha comprato una bicicletta nuova.',
  'I miei amici abitano vicino al mare.',
  'Il museo è chiuso il lunedì.',
  'Lei sorride e dice ciao.',
  'Aspettiamo da un\'ora.',
  'I prezzi sono saliti di nuovo.',
  'La sera suona la chitarra.',
  'La tua idea è molto buona.',
  'Il bambino finalmente dorme.',
  'Vado al mare con i miei amici.',
  'La cucina profuma di pane caldo.',
  'Ha dimenticato l\'ombrello.',
  'Lei ha superato l\'esame.',
  'Torniamo a casa.',
  'Che ore sono?',
  'Il giardino è pieno di fiori.',
  'Non si corre nel corridoio.',
  'Lei impara a nuotare.',
  'Il sabato il mercato è molto vivace.',
  'Ti chiamo domani mattina.',
  'Le stelle brillano nel cielo.',
  'Va al lavoro in metropolitana.',
  'La minestra è troppo salata.',
  'Abbiamo ballato tutta la notte.',
  'Lei mette in ordine la sua camera.',
  'D\'inverno il lago gela.',
  'Mi dispiace per il ritardo.',
  'Posa il bicchiere sul tavolo.',
  'Buona notte e a domani!',
  'Che bella giornata oggi!',
];

export default sentences;
