// Starter Polish sentences for sentence drills, written for this project
// (same license as the rest of the code). Short, everyday and made of common
// words, with Polish letters where they belong.
// `scripts/build-sentences.py pl` replaces this file with a larger set from
// Tatoeba (CC BY 2.0 FR).

const sentences: readonly string[] = [
  'Świeci słońce i niebo jest czyste.',
  'Ona czyta książkę w ogrodzie.',
  'Rano idziemy na targ.',
  'Dzieci bawią się w parku.',
  'On co rano pije filiżankę herbaty.',
  'Nasz pociąg odjeżdża o dziesiątej.',
  'Kot śpi na krześle.',
  'Muszę jeszcze kupić chleb i mleko.',
  'Droga jest długa, ale noc jest spokojna.',
  'Zamknij drzwi, kiedy wychodzisz.',
  'Usiedli na trawie i długo rozmawiali.',
  'To najlepsza zupa, jaką znam.',
  'Moja siostra maluje i rysuje.',
  'Pies biega po ogrodzie.',
  'Dziś wieczorem jemy kolację u rodziców.',
  'W weekend jedziemy nad jezioro.',
  'Podasz mi sól?',
  'Pada od samego rana.',
  'Dzisiaj nie mam czasu.',
  'Woda jest jeszcze bardzo zimna.',
  'Mieszka w małym domu na skraju miasta.',
  'Gdzie jest najbliższy dworzec?',
  'Ulica jest mokra od deszczu.',
  'Ona śpiewa bardzo ładną piosenkę.',
  'Jutro jedziemy na wakacje.',
  'Kawa jest dla mnie za gorąca.',
  'Jest późno, musimy wracać.',
  'Kwiaty w ogrodzie pięknie pachną.',
  'Mój brat pracuje w restauracji.',
  'Nie rozumiem tego pytania.',
  'Wszyscy przyszli na czas.',
  'Drzwi do sali są otwarte.',
  'Ona czeka na autobus przed pocztą.',
  'Ptaki śpiewają na drzewach.',
  'Szliśmy przez dwie godziny.',
  'Jesteś głodny?',
  'Sklep jest otwarty od dziewiątej.',
  'Wczoraj wieczorem zgubił klucze.',
  'Ona mówi w trzech językach.',
  'Obiad był naprawdę pyszny.',
  'Spotkajmy się przed kinem.',
  'Dziś wieczorem mocno wieje.',
  'Uczniowie słuchają nauczyciela.',
  'Wolę herbatę od kawy.',
  'Dzisiaj morze jest spokojne.',
  'Napisał list do matki.',
  'Potrzebujemy większego stołu.',
  'Film zaczyna się za dziesięć minut.',
  'Babcia piecze szarlotkę.',
  'Ona otworzyła okno.',
  'Zostało trochę chleba.',
  'Jesienią spadają liście.',
  'Idziesz z nami dziś wieczorem?',
  'Bardzo się cieszę, że cię widzę.',
  'Miasto jest piękne nocą.',
  'Co rano czyta gazetę.',
  'Pociąg jest spóźniony.',
  'Rozmawiamy o naszych planach.',
  'Znalazła na ulicy małego kotka.',
  'Jest ładna pogoda, chodźmy na spacer.',
  'Ta książka jest bardzo ciekawa.',
  'Dzieci wracają ze szkoły.',
  'Szukam okularów.',
  'Kolacja jest gotowa.',
  'Za mostem trzeba skręcić w lewo.',
  'Ona ma na sobie czerwoną sukienkę.',
  'Zwiedziliśmy stary zamek.',
  'Lekarz przyjdzie za godzinę.',
  'Rano wstaję wcześnie.',
  'Śnieg pokrywa góry.',
  'Kupił nowy rower.',
  'Moi przyjaciele mieszkają nad morzem.',
  'Muzeum jest zamknięte w poniedziałki.',
  'Ona uśmiecha się i mówi dzień dobry.',
  'Czekamy już od godziny.',
  'Ceny znowu poszły w górę.',
  'Wieczorem gra na gitarze.',
  'Twój pomysł jest bardzo dobry.',
  'Dziecko w końcu zasnęło.',
  'Idę na plażę z przyjaciółmi.',
  'W kuchni pachnie świeżym chlebem.',
  'Zapomniał parasola.',
  'Ona zdała egzamin.',
  'Wracamy do domu.',
  'Która jest godzina?',
  'Ogród jest pełen kwiatów.',
  'Na korytarzu nie wolno biegać.',
  'Ona uczy się pływać.',
  'W sobotę na targu jest dużo ludzi.',
  'Zadzwonię do ciebie jutro rano.',
  'Gwiazdy świecą na niebie.',
  'Jeździ do pracy metrem.',
  'Zupa jest za słona.',
  'Tańczyliśmy całą noc.',
  'Ona sprząta swój pokój.',
  'Zimą jezioro zamarza.',
  'Przepraszam za spóźnienie.',
  'Stawia szklankę na stole.',
  'Dobranoc i do jutra!',
  'Jaka piękna dziś pogoda!',
];

export default sentences;
