#!/usr/bin/env python3
"""Regenerate a frequency-ranked word list for one language.

Usage (from the repo root):
    python -m pip install "wordfreq==3.1.1"
    python scripts/build-corpus.py en 10000

Writes src/corpora/<lang>-words.ts. The word data comes from wordfreq
(https://github.com/rspeer/wordfreq), whose word lists are licensed under
CC BY-SA 4.0, so the generated file is too (see its header).
"""

import re
import sys
from importlib.metadata import version
from pathlib import Path

import wordfreq

# Letters a language's practice words may use. Words with digits, apostrophes,
# hyphens or other letters are left out until those keys are drilled.
LETTERS = {
    "en": "abcdefghijklmnopqrstuvwxyz",
}

# One-letter tokens that are real words; others ("s", "t", "m") come from
# split contractions and abbreviations.
SINGLE_LETTER_WORDS = {
    "en": {"a", "i"},
}

LINE_WIDTH = 100


def build(lang: str, count: int) -> list[str]:
    allowed = re.compile(f"^[{LETTERS[lang]}]+$")
    singles = SINGLE_LETTER_WORDS.get(lang, set())
    words: list[str] = []
    seen: set[str] = set()
    # Ask for extra so filtering still leaves `count` words.
    for w in wordfreq.top_n_list(lang, count * 3, wordlist="best"):
        if not allowed.match(w) or (len(w) == 1 and w not in singles) or w in seen:
            continue
        seen.add(w)
        words.append(w)
        if len(words) == count:
            return words
    raise SystemExit(f"only {len(words)} words found for {lang}")


def render(lang: str, words: list[str]) -> str:
    lines: list[str] = []
    line = ""
    for w in words:
        if line and len(line) + 1 + len(w) > LINE_WIDTH:
            lines.append(line)
            line = w
        else:
            line = f"{line} {w}" if line else w
    lines.append(line)
    body = "\n".join(lines)
    return f"""// GENERATED by scripts/build-corpus.py, do not edit by hand.
// Regenerate: python scripts/build-corpus.py {lang} {len(words)}
//
// The {len(words)} most frequent {lang} words, most frequent first, from wordfreq {version('wordfreq')}
// (https://github.com/rspeer/wordfreq, "best" list), keeping only plain lowercase letters.
//
// License: wordfreq's word list data is redistributable under CC BY-SA 4.0
// (https://creativecommons.org/licenses/by-sa/4.0/); this file is a derived work
// under the same license. wordfreq by Robyn Speer, built on data from Google Books
// Ngrams (http://books.google.com/ngrams), Wikipedia, the Leeds Internet Corpus,
// ParaCrawl, OPUS OpenSubtitles 2018 (http://www.opensubtitles.org/) and the SUBTLEX
// word lists by Marc Brysbaert et al., which are freely available data
// (http://crr.ugent.be/programs-data/subtitle-frequencies).

export default `
{body}
`;
"""


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    lang, count = sys.argv[1], int(sys.argv[2])
    if lang not in LETTERS:
        raise SystemExit(f"add the {lang} alphabet to LETTERS first")
    out = Path(__file__).resolve().parent.parent / "src" / "corpora" / f"{lang}-words.ts"
    out.write_text(render(lang, build(lang, count)), encoding="utf-8", newline="\n")
    print(f"wrote {count} words to {out}")


if __name__ == "__main__":
    main()
