#!/usr/bin/env python3
"""Build the sentence list for one language from Tatoeba.

Usage (from the repo root):
    python -m pip install "wordfreq==3.1.1"
    python scripts/build-sentences.py en 2000

Downloads the language's sentence export from Tatoeba (https://tatoeba.org),
keeps short sentences made of common words, and writes
src/corpora/<lang>-sentences.ts, replacing the hand-written starter set.
Tatoeba sentences are licensed under CC BY 2.0 FR, so the generated file is
too (see its header). Pass a local .tsv or .tsv.bz2 file as a third argument
to skip the download.
"""

import bz2
import json
import random
import re
import sys
import urllib.request
from pathlib import Path

import wordfreq

ROOT = Path(__file__).resolve().parent.parent

# Tatoeba uses ISO 639-3 codes.
TATOEBA_CODES = {
    "en": "eng",
    "de": "deu",
    "pl": "pol",
    "fr": "fra",
    "es": "spa",
    "it": "ita",
    "nl": "nld",
    "pt": "por",
}

# Letters a language's sentences may use (lowercase; capitals are allowed too).
LETTERS = {
    "en": "abcdefghijklmnopqrstuvwxyz",
    "de": "abcdefghijklmnopqrstuvwxyzäöüß",
}

# Languages that capitalise nouns, so a capital mid-sentence is not a name.
# Their sentences are kept unless they use a name from NAMES.
NOUN_CAPITALS = {"de"}

# Names Tatoeba's sentences use over and over.
NAMES = {"Tom", "Maria", "Mary", "John", "Ken", "Jim", "Bill", "Jack", "Mike", "Linda"}

# Words that are capitalised mid-sentence without being names.
ALWAYS_CAPITAL = {
    "en": {"I"},
}

PUNCTUATION = ".,?!;:'\"-"
MIN_CHARS, MAX_CHARS = 15, 80
# Every word must be at least this common (wordfreq Zipf scale; 3 is about once per million words).
MIN_ZIPF = 3.0
SEED = 1


def download(lang: str) -> Path:
    code = TATOEBA_CODES[lang]
    cache = ROOT / ".cache"
    cache.mkdir(exist_ok=True)
    path = cache / f"{code}_sentences.tsv.bz2"
    if not path.exists():
        url = f"https://downloads.tatoeba.org/exports/per_language/{code}/{code}_sentences.tsv.bz2"
        print(f"downloading {url}")
        urllib.request.urlretrieve(url, path)
    return path


def read_rows(path: Path):
    opener = bz2.open if path.suffix == ".bz2" else open
    with opener(path, "rt", encoding="utf-8") as f:
        for line in f:
            parts = line.rstrip("\n").split("\t")
            if len(parts) >= 3:
                yield parts[0], parts[2]


def blocked_terms(lang: str) -> set[str]:
    """LDNOOBW terms from the npm naughty-words package, if installed (npm install)."""
    path = ROOT / "node_modules" / "naughty-words" / f"{lang}.json"
    if not path.exists():
        print(f"warning: {path} not found, sentences are not checked for offensive words")
        return set()
    return {t.lower() for t in json.loads(path.read_text(encoding="utf-8"))}


def keep(text: str, lang: str, allowed: re.Pattern, blocked: set[str]) -> bool:
    if not MIN_CHARS <= len(text) <= MAX_CHARS or not allowed.match(text):
        return False
    words = re.findall(r"[^\W\d_]+(?:'[^\W\d_]+)*", text)
    if not words:
        return False
    # Names make poor practice text, and some sources repeat the same few endlessly.
    for i, w in enumerate(words):
        if w in NAMES:
            return False
        if lang not in NOUN_CAPITALS and i > 0 and w[0].isupper() and w not in ALWAYS_CAPITAL.get(lang, set()):
            return False
    lowered = [w.lower() for w in words]
    if any(wordfreq.zipf_frequency(w, lang) < MIN_ZIPF for w in lowered):
        return False
    joined = " " + " ".join(lowered) + " "
    return not any(f" {t} " in joined for t in blocked)


def build(lang: str, count: int, source: Path) -> list[tuple[str, str]]:
    letters = LETTERS[lang]
    allowed = re.compile(f"^[{letters}{letters.upper()} {re.escape(PUNCTUATION)}]+$")
    blocked = blocked_terms(lang)
    rows: list[tuple[str, str]] = []
    seen: set[str] = set()
    for sid, text in read_rows(source):
        text = " ".join(text.split())
        key = text.lower()
        if key in seen or not keep(text, lang, allowed, blocked):
            continue
        seen.add(key)
        rows.append((sid, text))
    if len(rows) < count:
        print(f"only {len(rows)} sentences pass the filters, keeping all of them")
        count = len(rows)
    random.Random(SEED).shuffle(rows)
    return sorted(rows[:count], key=lambda r: int(r[0]))


def render(lang: str, rows: list[tuple[str, str]]) -> str:
    body = "\n".join(f"  {json.dumps(text, ensure_ascii=False)}, // {sid}" for sid, text in rows)
    return f"""// GENERATED by scripts/build-sentences.py, do not edit by hand.
// Regenerate: python scripts/build-sentences.py {lang} {len(rows)}
//
// {len(rows)} short {lang} sentences of common words from Tatoeba (https://tatoeba.org).
// Each line ends with its Tatoeba sentence id: https://tatoeba.org/sentences/show/<id>
// shows the sentence and its author.
//
// License: Tatoeba sentences are licensed under CC BY 2.0 FR
// (https://creativecommons.org/licenses/by/2.0/fr/); this file is a derived work under
// the same license. Sentences © their Tatoeba contributors.

const sentences: readonly string[] = [
{body}
];

export default sentences;
"""


def main() -> None:
    if len(sys.argv) not in (3, 4):
        raise SystemExit(__doc__)
    lang, count = sys.argv[1], int(sys.argv[2])
    if lang not in LETTERS or lang not in TATOEBA_CODES:
        raise SystemExit(f"add {lang} to LETTERS and TATOEBA_CODES first")
    source = Path(sys.argv[3]) if len(sys.argv) == 4 else download(lang)
    rows = build(lang, count, source)
    out = ROOT / "src" / "corpora" / f"{lang}-sentences.ts"
    out.write_text(render(lang, rows), encoding="utf-8", newline="\n")
    print(f"wrote {len(rows)} sentences to {out}")


if __name__ == "__main__":
    main()
